### ISSUE TITLE
Parameter server

### ISSUE THREAD

**Issue by nim65s** [stack-of-tasks/talos_integration_tests#22]
Hi @olivier-stasse,

Since https://github.com/stack-of-tasks/sot-core/pull/156, when I launch the test kine, I have:
```
 Read Sot Vector State Param 
[ WARN] [1599048510.382045619, 1.534000000]: initRequest 1
[ WARN] [1599048510.423041666, 1.548000000]: No parameter /sot_controller/effort_controler_pd_motor_init
[ WARN] [1599048510.423389623, 1.548000000]: No parameter /sot_controller/velocity_controler_pd_motor_init
[ WARN] [1599048510.423722108, 1.549000000]: initRequest 2
[ERROR] [1599048510.429919441, 1.550000000]: Wrong initialization of parameter_name /robot_description
[ WARN] [1599048510.431565747, 1.550000000]: initRequest 3
[ WARN] [1599048510.898135668, 1.771000000]: initRequest 4
[ERROR] [1599048512.235835262, 2.533000000]: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "…/site-packages/dynamic_graph/sot/pyrene/prologue.py", line 29, in makeRobot
    robot = Robot(name='talos', device=DeviceTalos('PYRENE'), fromRosParam=True)
  File "…/site-packages/dynamic_graph/sot/pyrene/robot.py", line 51, in __init__
    Talos.__init__(self, name, device=device, tracer=tracer, fromRosParam=fromRosParam)
  File "…/site-packages/dynamic_graph/sot/talos/talos.py", line 75, in __init__
    self.param_server.init_simple(ltimeStep)
RuntimeError: No robot registered in the parameter server list listOfRobots->size: 0
```

The first ERROR comes from here: https://github.com/stack-of-tasks/dynamic_graph_bridge/blob/master/src/ros_parameter.cpp#L45

Is anything missing in talos_integration_test, eg. to publish an URDF to `/robot_description` before launching the test ?

**Comment by olivier-stasse** [comment]
Yes sorry this is due to a stupid bug in dynamic_graph/src/ros_parameter.cpp that I forgot to push.
https://github.com/stack-of-tasks/dynamic_graph_bridge/blob/a41d26998383b20b0f55045ebedf4c42c4e84efb/src/ros_parameter.cpp#L33 should == instead of !=

**Comment by nim65s** [comment]
Ok, let's try this :)

**Comment by nim65s** [comment]
Fixed, thanks !
